language: node_js
node_js:
- 8
cache:
  directories:
  - web-react/node_modules
script:
- sh build-web-react.sh
deploy:
  skip_cleanup: true
  provider: script
  script: deploy-web-react.sh
  on:
    branch: master