language: node_js
node_js:
- 8
cache:
  directories:
  - web-react/node_modules
script:
- sh build-web-react.sh
deploy:
  skip_cleanup: true
  provider: s3
  local_dir: web-react/build
  on:
    branch: master
  bucket: nsfwnsfw-web-react-prod
  access_key_id: "AKIAIOQMFHFMNBHNJFIA"
  secret_access_key:
    secure: Ga3sv/w2hxnr9gQX5EocmhUFJgfEKR/8E53OSaS4e3KXVoA3g8QK82/+fMRRf8DlfELOmZUopl85arjuyGOL2QLvJO1gew5I/mmPwGQR+Ifp0mKX79V5Gx9nWzo9kTo5z+BPkCVL4nWldk+EelEjsg7ma9h4Udvv98YXnLJGUdrAiJ/hQI/D00PvdsVEknupNsQrPGkCKAU8gugCjWUbVj2cziTKlBZWmPsqjU8ZU5UgS2uMDz+W80/6zUBPyQuwWeHKSrwvR+bdSRUrtO07td4vcI0pVBi5FbbI2tuFKF0rPzJWzOenZpPpg1wA5k0twgJVSn6bNUbbDwsULwR8NnobW55JBVLc721a5Yj34hPaiguHwMKHNxtwvLJZdtx99ET5erSQdyGeEYX7vL2A/tS3Vaog36lBGEC9bcKwV3kPPnnUcpH9AiLbj5wGkPhOoxFmCjLjyfqCevOz9GrTDuW3d2+FWysA/vWc5U24qIPbuDy56RruPPXVD0RiBxFsCpLpX/5HPFE0HZEbzUlXisBmJgQ7Q2WoiWe0Oex32ubKXyjVSdrecDXNaUkAR5DEsU3brqpbYD8vVFrgJoBVgLvKPSVD6CS+9tAxO21kB5TVvYBiq3lSjEGHDh/MVNSTb784nFO4ZwE/se2kbDv7/Gjafm04agkJ/lGCuomk7vM=
